//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Class1
{
	public virtual int Id
	{
		get;
		set;
	}

	public virtual string Name
	{
		get;
		set;
	}

	public virtual int Age
	{
		get;
		set;
	}

	public virtual string Menpai
	{
		get;
		set;
	}

	public virtual string Kungfu
	{
		get;
		set;
	}

	public virtual int Level
	{
		get;
		set;
	}

}

